name: Setup
inputs:
  init-test:
    description: 'Whether to init test'
    required: false
  run-id:
    description: 'id of the workflow run'
    required: false
    type: string
runs:
  using: 'composite'
  steps:
    - name: Print github context
      shell: bash
      run: |
        echo "github.actor: ${{ github.actor }}"
        echo "github.triggering_actor: ${{ github.triggering_actor }}"
        echo "github.event: ${{ toJSON(github.event) }}"

    - name: Setup pnpm
      # Must not set shell for other actions...
      uses: pnpm/action-setup@v4
      with:
        version: 9.9.0

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install
      shell: bash # Must set shell for every step in composite action...
      run: pnpm install --frozen-lockfile

    - name: Check inputs
      shell: bash
      run: |
        echo "github.event.inputs: ${{ toJSON(github.event.inputs) }}"
        echo "inputs: ${{ toJSON(inputs) }}"

    - name: Check if needs to init test
      shell: bash
      if: ${{ inputs.init-test == true || inputs.init-test == 'true' }}
      run: pnpm exec playwright install

    # - name: Check if needs to download build
    #   uses: actions/download-artifact@v4
    #   if: ${{ inputs.run-id }}
    #   with:
    #     name: package-builds
    #     path: ./packages
    #     run-id: ${{ inputs.run-id }}

    # official download-artifact doesn't support download artifact from another workflow run, don't why, use below instead
    - name: Check if needs to download build
      uses: dawidd6/action-download-artifact@v6
      if: ${{ inputs.run-id }}
      with:
        name: package-builds
        path: ./packages
        run_id: ${{ inputs.run-id }}
