packages:
  - 'packages/*'

catalog:
  vite: ^5.4.6
  vite-plugin-dts: ^3.9.1
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  vitest: ^2.0.1
  vue: ^3.5.7
  '@vue/runtime-dom': ^3.5.7
  '@vue/runtime-core': ^3.5.7
  '@vue/compiler-core': ^3.5.7
  vue-tsc: ^2.1.6
  react: rc
  react-dom: rc
  typescript: ^5.6.2
  rimraf: ^5.0.7
  cross-env: ^7.0.3
  '@rollup/plugin-replace': ^5.0.7
  postcss-logical: ^7.0.1
  sass: ^1.77.6
  '@floating-ui/dom': ^1.6.7
  '@floating-ui/utils': ^0.2.4
  '@floating-ui/vue': ^1.1.1
