packages:
  - 'packages/*'

catalog:
  vite: ^6.2.2
  vite-plugin-dts: ^4.3.0
  '@vitejs/plugin-vue': ^5.2.3
  '@vitejs/plugin-vue-jsx': ^4.1.2
  vitest: 3.0.9
  vue: ^3.5.13
  '@vue/runtime-dom': ^3.5.13
  '@vue/runtime-core': ^3.5.13
  '@vue/compiler-core': ^3.5.13
  vue-tsc: ^2.2.8
  react: ^19
  react-dom: ^19
  typescript: ^5.6.3
  rimraf: ^6.0.1
  cross-env: ^7.0.3
  '@rollup/plugin-replace': ^6.0.1
  postcss-logical: ^7.0.1
  sass-embedded: '^1.81.0'
  '@floating-ui/dom': ^1.6.7
  '@floating-ui/utils': ^0.2.4
  '@floating-ui/vue': ^1.1.1
