packages:
  - 'packages/*'

catalog:
  vite: ^5.4.10
  vite-plugin-dts: ^4.3.0
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  vitest: 2.1.4
  vue: ^3.5.12
  '@vue/runtime-dom': ^3.5.12
  '@vue/runtime-core': ^3.5.12
  '@vue/compiler-core': ^3.5.12
  vue-tsc: ^2.1.6
  react: rc
  react-dom: rc
  typescript: ^5.6.3
  rimraf: ^6.0.1
  cross-env: ^7.0.3
  '@rollup/plugin-replace': ^5.0.7
  postcss-logical: ^7.0.1
  sass-embedded: '^1.80.4'
  '@floating-ui/dom': ^1.6.7
  '@floating-ui/utils': ^0.2.4
  '@floating-ui/vue': ^1.1.1
