import {
  debounce,
  isElement,
  ensureArray,
  on,
  off,
  noop,
  isEditElement,
  getDeepestActiveElement,
  inBrowser,
  getWindow,
  isNode,
  toHostIfSlot,
  runIfFn,
  prevent,
  setIntersectOrHas,
  getRect,
} from '@lun-web/utils';
import { computed, nextTick, reactive, ref, watch, watchEffect } from 'vue';
import { VirtualElement, tryOnScopeDispose, useClickOutside, useMounted } from '../../hooks';
import { objectComputed, unrefOrGet, unrefOrGetMulti } from '../../utils';
import { useListen } from './useListen';
import { createPopoverRectTarget } from './utils';
import { PopoverAttachTargetOptions, PopoverTrigger, UsePopoverOptions } from './type';

export function usePopover(_options: UsePopoverOptions) {
  const isOpen = ref(false),
    /** it's for animation; isOpen: false => animation ends => isShow: false */ isShow = ref(false),
    isCloseScheduling = ref(false);
  const isClosing = computed(() => isCloseScheduling.value || (!isOpen.value && isShow.value));
  const virtualTarget = ref<
    | (VirtualElement & {
        /**
         * this flag indicates the virtual target is generated by pointer or not.
         * it's to prevent selection clearing the target generated by pointer as selection target and pointer target share the virtualTarget ref.
         */
        _p?: boolean;
      })
    | null
    | undefined
  >();

  let ensureClose: boolean | undefined = false; // flag used to ensure delayed close
  const options = objectComputed(() => {
    let { openDelay = 0, closeDelay = 120, onOpen, triggers, disabled, beforeOpen } = _options;
    const performOpen = () => {
      if (unrefOrGet(disabled) || unrefOrGet(isOpen) || runIfFn(beforeOpen, actualTarget.value as any) === false)
        return;
      const result = onOpen();
      if (result !== undefined) isShow.value = isOpen.value = result;
    };
    const performClose = () => {
      isOpen.value = false;
      ensureClose = false;
    };

    const dOpen = debounce(performOpen, openDelay),
      dClose = debounce(performClose, closeDelay, { onSchedulingUpdate: (v) => (isCloseScheduling.value = v) });
    triggers = ensureArray(triggers!);
    if (!triggers.length) triggers = ['hover', 'click', 'edit'];
    const cancelOpenOrClose = () => {
      dOpen.cancel();
      dClose.cancel();
    };
    return {
      targetFocusThreshold: 20,
      get manual() {
        return _options.open !== undefined;
      },
      triggers: new Set<PopoverTrigger>(triggers),
      cancelOpenOrClose,
      open() {
        if (ensureClose === true) return;
        dClose.cancel();
        dOpen();
        events?.onOpen();
      },
      close(ensure?: boolean) {
        dOpen.cancel();
        dClose();
        ensureClose = ensure;
      },
      openNow() {
        cancelOpenOrClose();
        performOpen();
      },
      closeNow() {
        cancelOpenOrClose();
        performClose();
      },
      toggleNow(force?: boolean) {
        cancelOpenOrClose();
        if (!isOpen.value || (!force && force !== undefined)) performOpen();
        else if (isOpen.value || force) performClose();
      },
    };
  });

  const events = useListen({
    // always open parent when child opens, it's for nested type=teleport popover
    onOpen: () => options.open(),
    // we can't close parent when child closes, should use onPopContentClose and let parent to handle it
    // onClose: () => options.value.close(),
  });

  // handle manual open control by external
  const mounted = useMounted();
  watchEffect(() => {
    const { manual, openNow, closeNow } = options;
    if (manual && mounted.value) {
      if (_options.open) openNow();
      else closeNow();
    }
  });

  /** create a event handler representing a pop trigger with action method */
  const createTrigger =
    (
      trigger: PopoverTrigger | null | Set<PopoverTrigger>,
      method: 'open' | 'close' | 'toggle',
      /** return false to prevent trigger; return open or close to change the default method */
      extraHandle?: (e: Event, actualMethod: 'open' | 'close') => void | boolean | 'open' | 'close',
    ) =>
    (e: Event) => {
      const { triggers, manual } = options;
      // 'edit' same as 'focus'
      if (
        (!trigger || setIntersectOrHas(triggers, trigger) || (trigger === 'focus' && triggers.has('edit'))) &&
        !manual
      ) {
        let actualMethod =
          method === 'toggle' ? (_options.toggleMode && unrefOrGet(isShow) ? 'close' : 'open') : method;
        let temp: any = '';
        if (extraHandle && (temp = extraHandle(e, actualMethod)) === false) return;
        const finalMethod = (options as any)[temp] || options[actualMethod];
        // clear selection target
        if (trigger !== 'select' && finalMethod === 'open' && !virtualTarget.value?._p) virtualTarget.value = null;
        finalMethod();
      }
    };

  let popFocusIn = false,
    ignoreTargetFocusout = false;
  /** focusing elements inside popover target, or popover target itself */
  const focusSet = new WeakSet<EventTarget>(),
    focusDeepestElMap = new WeakMap<Element, Element>();

  /** determine whether to prevent closing pop content(checkTrigger=true) or prevent switching pop target(checkTrigger=false) when has focus */
  const needPrevent = (e: Event, checkTrigger = true) => {
    const { triggers } = options,
      { preventSwitchWhen } = _options;
    const deepEl = getDeepestActiveElement()!;
    return (
      unrefOrGet(isShow) &&
      (popFocusIn || focusSet.has(e.target!) || focusSet.has(deepEl)) &&
      ((checkTrigger ? triggers.has('focus') : preventSwitchWhen === 'focus') ||
        ((checkTrigger ? triggers.has('edit') : preventSwitchWhen === 'edit') && isEditElement(deepEl)))
    );
  };

  // ------------------ extra targets ------------------
  // it's to support attaching events of triggering popover on other elements in an imperative manner
  const extraTargetsMap = reactive(new Map<Element, ReturnType<typeof createTargetHandlers>>()),
    extraTargetsOptionMap = reactive(new WeakMap<Element, PopoverAttachTargetOptions>());
  const activeExtraTarget = ref<Element>(),
    activeExtraTargetOptions = computed(() => extraTargetsOptionMap.get(activeExtraTarget.value!));
  const methods = {
    attachTarget(target?: Element, options: PopoverAttachTargetOptions = {}) {
      let originalOptions = extraTargetsOptionMap.get(target!);
      if (!isElement(target)) return;
      if (originalOptions && originalOptions !== options) {
        extraTargetsOptionMap.set(target, options);
        return;
      }
      const targetHandlers = createTargetHandlers((e, method) => {
        if (method === 'open') {
          if (unrefOrGet(extraTargetsOptionMap.get(target)?.isDisabled)) return false;
          // consider pointerdown also as focusin, or pointerdown can be prevented because of needPrevent when switching targets
          if (e.type !== 'focusin' && e.type !== 'pointerdown' && needPrevent(e, false)) {
            return false;
          }
          activeExtraTarget.value = target;
        }
        // no need to clear activeTarget when close, as every open will reset activeTarget
      });
      extraTargetsMap.set(target, targetHandlers);
      extraTargetsOptionMap.set(target, options);
      for (const [key, handler] of Object.entries(targetHandlers)) {
        on(target, key.slice(2).toLowerCase(), handler);
      }
    },
    detachTarget(target?: Element) {
      if (!isElement(target)) return;
      const targetHandlers = extraTargetsMap.get(target);
      if (!targetHandlers) return;
      for (const [key, handler] of Object.entries(targetHandlers)) {
        off(target, key.slice(2).toLowerCase(), handler);
      }
      extraTargetsMap.delete(target);
      extraTargetsOptionMap.delete(target);
      if (target === activeExtraTarget.value) {
        options.closeNow();
        activeExtraTarget.value = undefined;
      }
    },
    detachAll() {
      for (const target of extraTargetsMap.keys()) {
        methods.detachTarget(target);
      }
    },
  };
  tryOnScopeDispose(methods.detachAll);
  // ------------------ extra targets ------------------

  const createTargetHandlers = (onTrigger: (e: Event, actualMethod: 'open' | 'close') => void | boolean = noop) => {
    let targetFocusInTime = 0,
      targetFocusOutTime = 0,
      pointerDownTime = 0;

    const activatePointerTarget = (e: MouseEvent, triggerResult?: boolean | void) => {
      if (triggerResult !== false && _options.pointerTarget === 'coord') {
        // do not use clientX, use offsetX + target rect x instead, and make sure getBoundingClientRect is dynamic, in case target updates its position(e.g. scrolling)
        const tx = e.offsetX,
          ty = e.offsetY,
          t = e.target as Element;
        virtualTarget.value = {
          _p: true,
          ...createPopoverRectTarget(() => {
            const { x, y } = getRect(t);
            return [tx + x, ty + y];
          }),
        };
      } else virtualTarget.value = undefined;
      return triggerResult;
    };

    const pointerdownClose = createTrigger('pointerdown', 'close', onTrigger);
    const targetHandlers = {
      onMouseenter: createTrigger('hover', 'open', onTrigger),
      onMouseleave: createTrigger('hover', 'close', (e, m) => {
        return !needPrevent(e) && onTrigger(e, m) !== false;
      }),
      // need to use pointer down to trigger toggle before focusin
      onPointerdown: createTrigger(new Set(['click', 'pointerdown']), 'toggle', (e, m) => {
        pointerDownTime = e.timeStamp;
        // focusin should be triggered after pointerdown
        // but found an exception... if we focus on target and then focus other place outside viewport(like browser address input or console input), then click target again
        // it will fire focusin first and then pointerdown, no idea why...
        // so prevent focusin firing when it's before pointerdown
        const { targetFocusThreshold } = options;
        if (pointerDownTime - targetFocusInTime < targetFocusThreshold) return false;
        return activatePointerTarget(e as MouseEvent, onTrigger(e, m));
      }),
      onPointerup: pointerdownClose,
      onPointerleave: pointerdownClose,
      onPointercancel: pointerdownClose,
      onContextmenu: createTrigger('contextmenu', 'open', (e, m) => {
        prevent(e);
        return activatePointerTarget(e as MouseEvent, onTrigger(e, m));
      }),
      onFocusin: createTrigger('focus', 'open', (e, m) => {
        targetFocusInTime = e.timeStamp;
        const target = e.target as Element,
          cur = e.currentTarget as Element,
          deep = getDeepestActiveElement()!;
        focusSet.add(target);
        focusSet.add(cur); // it's to prevent hiding in other events like mouseleave. their target may differ, but currentTarget is always the popover target
        focusSet.add(deep); // it's to prevent switching when focus or edit, use deepest element because custom-element can be inside another custom-element
        focusDeepestElMap.set(target, deep);

        // if we click suffix icon when input is focused and toggleMode is true, it will fire pointerdown(toggle close) -> focusout -> focusin(open). close will be canceled
        // we need to prevent this
        // if (targetFocusInTime - pointerDownTime < options.targetFocusThreshold) return false; // targetFocusInTime - pointerDownTime is not reliable, it can be 10+ms or 20+ms, use isShow instead
        // if (unrefOrGet(options.isShow) && !extraTargetsMap.value.has(e.currentTarget as any)) return false;
        if (isClosing.value && !extraTargetsMap.has(cur)) {
          return false;
        }
        return onTrigger(e, m);
      }),
      onFocusout: createTrigger('focus', 'close', (e, m) => {
        targetFocusOutTime = e.timeStamp;
        const target = e.target as Element,
          cur = e.currentTarget as Element,
          deep = focusDeepestElMap.get(target)!;
        focusSet.delete(target);
        focusSet.delete(deep);
        focusSet.delete(cur);
        const { targetFocusThreshold } = options;
        if (ignoreTargetFocusout || targetFocusOutTime - pointerDownTime < targetFocusThreshold) return false;
        return onTrigger(e, m);
      }),
    };
    return targetHandlers;
  };

  const handlePopShow = createTrigger(null, 'open'),
    contentClose = (e: Event) => _options.onPopContentClose?.(e),
    pointerdownClose = createTrigger('pointerdown', 'close', contentClose);
  const popContentHandlers = {
    onMouseenter: handlePopShow,
    onMouseleave: createTrigger('hover', 'close', (e) => {
      const res = !needPrevent(e);
      if (res !== false) contentClose(e);
      return res;
    }),
    // focusin bubbles, while focus doesn't
    onFocusin: createTrigger(null, 'open', () => {
      popFocusIn = true;
    }),
    onFocusout: createTrigger(null, 'close', (e) => {
      popFocusIn = false;
      contentClose(e);
    }),
    // need use pointerdown instead of click, because if we press the pop content and don't release, popover target will fire focusout and then close, click will not be triggered on pop content
    onPointerdown(e: Event) {
      ignoreTargetFocusout = true;
      // to make sure it's after focusout
      setTimeout(() => {
        handlePopShow(e);
      });
    },
    onPointerup: pointerdownClose,
    onPointerleave: pointerdownClose,
    onPointercancel: pointerdownClose,
  };

  const addClean = useClickOutside(
    computed(() =>
      // Array.from(extraTargetsMap.value.keys()).concat(options.target as any, options.pop as any),
      [activeExtraTarget.value, _options.target, _options.pop],
    ),
    () => {
      options.close();
      ignoreTargetFocusout = false;
    },
    () => {
      const { manual } = options;
      return unrefOrGet(isShow) && !manual;
    },
  );

  // ------------------ selection ------------------
  const handleSelect = createTrigger('select', 'open', (e) => {
    const selection = getWindow(e.target as any).getSelection();
    // FIXME try using popover for callout's description, it doesn't work because of selection in shadow DOM
    if (!selection || selection.type !== 'Range') {
      // virtualTarget.value = null; // do not clear virtualTarget here, if we clear it, actual pop target will update and then position shifts. we delay it to next open in createTrigger.
      return 'close';
    }
    // options.target is a slot element, seems that slot element is always false when calling containsNode, so we need to get the host element
    const target = [toHostIfSlot(unrefOrGet(_options.target)), ...extraTargetsMap.keys()].find(
      (e) => isNode(e) && selection.containsNode(e, true),
    );
    if (target) {
      virtualTarget.value = selection.getRangeAt(0);
    } else {
      // virtualTarget.value = null;
      return 'close';
    }
  });
  const stop = watchEffect(
    () => {
      if (inBrowser && options.triggers.has('select')) {
        addClean(on(document, 'selectionchange', handleSelect));
        nextTick(() => stop()); // must in nextTick, as we can't call stop before initialization
      }
    },
    { flush: 'sync' },
  );
  // ------------------ selection ------------------

  const actualTarget = computed(
    () => unrefOrGetMulti(virtualTarget, activeExtraTarget, _options.target) as Element | VirtualElement | undefined,
  );
  watch(
    actualTarget,
    (val, old) => {
      if (runIfFn(_options.afterTargetUpdate, val, old) === false) options.closeNow();
    },
    { flush: 'sync' },
  );

  return {
    targetHandlers: createTargetHandlers((e, method) => {
      // when extra target is under popover and event bubbles, both extra and popover itself will be triggered to open, we shouldn't clearing activeExtraTarget at that time
      if (method === 'open' && e.target !== activeExtraTarget.value) activeExtraTarget.value = undefined;
    }),
    popContentHandlers,
    options,
    methods,
    activeExtraTarget,
    activeExtraTargetOptions,
    /** current valid selection range or pointer target ref */
    virtualTarget,
    isOpen,
    isShow,
    isClosing,
    actualTarget,
  };
}
