name: Packages build

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      docs:
        description: 'Deploy docs'
        required: false
        default: false
        type: boolean
      publish:
        description: 'Publish packages'
        required: false
        default: false
        type: boolean

# must have permissions same as call_docs
permissions:
  pull-requests: write # for publish
  contents: write
  pages: write
  id-token: write

jobs:
  build_packages:
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && !contains(github.event.head_commit.message, '[build skip]') }}
    runs-on: ubuntu-22.04
    outputs:
      run-id: ${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # need to checkout before using it...
      - name: Setup
        uses: ./.github/actions/setup # must use directory, and action.yml must be there
      - name: Build
        run: pnpm build
      - name: Archive production artifacts
        id: artifacts-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: package-builds
          overwrite: true
          path: |
            packages/*/dist/**/*

  call_test:
    needs: build_packages
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && !contains(github.event.head_commit.message, '[test skip]')}}
    uses: ./.github/workflows/test.yml
    with:
      run-id: ${{ github.run_id }}
    secrets: inherit # must explicitly inherit secrets

  call_docs:
    needs: build_packages
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && (contains(github.event.head_commit.message, '[deploy docs]') || inputs.docs) && github.repository == 'lejunyang/lun' }}
    uses: ./.github/workflows/docs.yml
    with:
      run-id: ${{ github.run_id }}
    secrets: inherit

  call_publish:
    needs: build_packages
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && github.repository == 'lejunyang/lun' && ((contains(github.event.head_commit.message, '[publish]') && github.actor == 'lejunyang') || (startsWith(github.event.head_commit.message, 'Version Packages') && github.actor == 'github-actions[bot]') || inputs.publish) }}
    uses: ./.github/workflows/publish.yml
    with:
      run-id: ${{ github.run_id }}
    secrets: inherit
