name: Packages build

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# must have permissons same as call_docs
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_packages:
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && !contains(github.event.head_commit.message, '[build skip]') }}
    runs-on: ubuntu-22.04
    outputs:
      artifact-id: ${{ steps.artifacts-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # need to checkout before using it...
      - name: Setup
        uses: ./.github/actions/setup # must use directory, and action.yml must be there
      - name: Build
        run: pnpm build
      - name: Archive production artifacts
        id: artifacts-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: package-builds
          overwrite: true
          path: |
            packages/*/dist/**/*

  call_test:
    needs: build_packages
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && !contains(github.event.head_commit.message, '[test skip]')}}
    uses: ./.github/workflows/test.yml
    with:
      artifact-id: ${{ needs.build_packages.outputs.artifact-id }}
    secrets: inherit # must explicitly inherit secrets

  call_docs:
    needs: build_packages
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && contains(github.event.head_commit.message, '[deploy docs]') && github.repository == 'lejunyang/lun' }}
    uses: ./.github/workflows/docs.yml
    with:
      artifact-id: ${{ needs.build_packages.outputs.artifact-id }}
    secrets: inherit
