name: Test after build

on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string

jobs:
  after_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package-builds
          run-id: ${{ inputs.artifact-id }}
      - run: ls -R packages/components
      - run: echo "LIST ROOT"
      - run: ls .