name: Component tests

on: 
  workflow_dispatch:
    inputs:
      artifact-id:
        required: true
        type: string
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[all skip]') && !contains(github.event.head_commit.message, '[test skip]') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: ./.github/actions/setup.yml
        with:
          artifact-id: ${{ inputs.artifact-id }}
          init-test: true

      - name: Run Tests
        run: pnpm test run

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
